---

- name: configs > Templates
  template:
    src:   "{{ item.template }}"
    dest:  "{{ bind_configs_dir }}/{{ item.file }}"
    owner: root
    group: "{{ bind_group }}"
    mode:  0644
  with_items: '{{ bind_configs }}'
  notify:
    - bind restart
