---

- name: logrotate > Template base
  template:
    src:   logrotate/base.j2
    dest:  "{{ bind_logrotate_file }}"
    owner: root
    group: root
    mode:  0644
  when: (bind_logrotate_template is none) and (not bind_logrotate_config|length)

- name: logrotate > Template
  template:
    src:   "{{ bind_logrotate_template|ternary(bind_logrotate_template, 'logrotate/empty.j2') }}"
    dest:  "{{ bind_logrotate_file }}"
    owner: root
    group: root
    mode:  0644
  when: (bind_logrotate_template is not none) or (bind_logrotate_config|length)
